url: http://www.chinatopup.com
baseurl: ""
permalink: /:title/

# Site settings
title: China Topup | Alipay | Wechat | Mipay
email: xinming.creative@gmail.com
description: "We provide top up services for alipay, wechat, and mipay."
keywords: "alipay, wechat, mipay, top up, china"

# Plugins
# gems:
#   - jekyll-multiple-languages-plugin

# Language
languages: ["en", "cn"]
# exclude_from_localizations: ["js", "img", "css", "stylesheets", "favicon.ico"]

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:xinming.creative@gmail.com
  - title: twitter
    url: http://twitter.com/xinmingcreative
  - title: facebook
    url: https://www.facebook.com/China-Topup-1733788990273408/
  - title: google-plus
    url: https://plus.google.com/u/0/111553672648702640277
  - title: wechat
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: redcarpet
permalink: pretty
# highlighter: pygments
